package com.wannacall.countrypicker

import wc_country_picker.countrypicker.generated.resources.Res
import wc_country_picker.countrypicker.generated.resources.*

/**
 * The `Countries` object is a singleton that contains a collection of predefined `Country` objects.
 * Each `Country` object contains information about a specific country, including its name,
 * ISO country code, dialing code, and the associated flag drawable resource.
 *
 * The `Countries` object can be used to access country data by calling the properties corresponding
 * to each country, which are initialized as instances of the `Country` class.
 */
object Countries {
    val AD = Country("Andorra", "AD", "+376", Res.drawable.ad)
    val AE = Country("United Arab Emirates", "AE", "+971", Res.drawable.ae)
    val AF = Country("Afghanistan", "AF", "+93", Res.drawable.af)
    val AG = Country("Antigua and Barbuda", "AG", "+1", Res.drawable.ag)
    val AI = Country("Anguilla", "AI", "+1", Res.drawable.ai)
    val AL = Country("Albania", "AL", "+355", Res.drawable.al)
    val AM = Country("Armenia", "AM", "+374", Res.drawable.am)
    val AO = Country("Angola", "AO", "+244", Res.drawable.ao)
    val AQ = Country("Antarctica", "AQ", "+672", Res.drawable.aq)
    val AR = Country("Argentina", "AR", "+54", Res.drawable.ar)
    val AS = Country("American Samoa", "AS", "+1", Res.drawable.`as`)
    val AT = Country("Austria", "AT", "+43", Res.drawable.at)
    val AU = Country("Australia", "AU", "+61", Res.drawable.au)
    val AW = Country("Aruba", "AW", "+297", Res.drawable.aw)
    val AX = Country("Åland Islands", "AX", "+358", Res.drawable.ax)
    val AZ = Country("Azerbaijan", "AZ", "+994", Res.drawable.az)
    val BA = Country("Bosnia and Herzegovina", "BA", "+387", Res.drawable.ba)
    val BB = Country("Barbados", "BB", "+1", Res.drawable.bb)
    val BD = Country("Bangladesh", "BD", "+880", Res.drawable.bd)
    val BE = Country("Belgium", "BE", "+32", Res.drawable.be)
    val BF = Country("Burkina Faso", "BF", "+226", Res.drawable.bf)
    val BG = Country("Bulgaria", "BG", "+359", Res.drawable.bg)
    val BH = Country("Bahrain", "BH", "+973", Res.drawable.bh)
    val BI = Country("Burundi", "BI", "+257", Res.drawable.bi)
    val BJ = Country("Benin", "BJ", "+229", Res.drawable.bj)
    val BL = Country("Saint Barthélemy", "BL", "+590", Res.drawable.bl)
    val BM = Country("Bermuda", "BM", "+1", Res.drawable.bm)
    val BN = Country("Brunei Darussalam", "BN", "+673", Res.drawable.bn)
    val BO = Country("Bolivia", "BO", "+591", Res.drawable.bo)
    val BR = Country("Brazil", "BR", "+55", Res.drawable.br)
    val BS = Country("Bahamas", "BS", "+1", Res.drawable.bs)
    val BT = Country("Bhutan", "BT", "+975", Res.drawable.bt)
    val BV = Country("Bouvet Island", "BV", "+47", Res.drawable.bv)
    val BW = Country("Botswana", "BW", "+267", Res.drawable.bw)
    val BY = Country("Belarus", "BY", "+375", Res.drawable.by)
    val BZ = Country("Belize", "BZ", "+501", Res.drawable.bz)
    val CA = Country("Canada", "CA", "+1", Res.drawable.ca)
    val CC = Country("Cocos (Keeling) Islands", "CC", "+61", Res.drawable.cc)
    val CD = Country("Congo, The Democratic Republic of the", "CD", "+243", Res.drawable.cd)
    val CF = Country("Central African Republic", "CF", "+236", Res.drawable.cf)
    val CG = Country("Congo", "CG", "+242", Res.drawable.cg)
    val CH = Country("Switzerland", "CH", "+41", Res.drawable.ch)
    val CI = Country("Côte d'Ivoire", "CI", "+225", Res.drawable.ci)
    val CK = Country("Cook Islands", "CK", "+682", Res.drawable.ck)
    val CL = Country("Chile", "CL", "+56", Res.drawable.cl)
    val CM = Country("Cameroon", "CM", "+237", Res.drawable.cm)
    val CN = Country("China", "CN", "+86", Res.drawable.cn)
    val CO = Country("Colombia", "CO", "+57", Res.drawable.co)
    val CR = Country("Costa Rica", "CR", "+506", Res.drawable.cr)
    val CU = Country("Cuba", "CU", "+53", Res.drawable.cu)
    val CV = Country("Cape Verde", "CV", "+238", Res.drawable.cv)
    val CW = Country("Curaçao", "CW", "+599", Res.drawable.cw)
    val CX = Country("Christmas Island", "CX", "+61", Res.drawable.cx)
    val CY = Country("Cyprus", "CY", "+357", Res.drawable.cy)
    val CZ = Country("Czech Republic", "CZ", "+420", Res.drawable.cz)
    val DE = Country("Germany", "DE", "+49", Res.drawable.de)
    val DJ = Country("Djibouti", "DJ", "+253", Res.drawable.dj)
    val DK = Country("Denmark", "DK", "+45", Res.drawable.dk)
    val DM = Country("Dominica", "DM", "+1", Res.drawable.dm)
    val DZ = Country("Algeria", "DZ", "+213", Res.drawable.dz)
    val EAC = Country("East Africa", "EAC", "+255", Res.drawable.eac)
    val EC = Country("Ecuador", "EC", "+593", Res.drawable.ec)
    val EE = Country("Estonia", "EE", "+372", Res.drawable.ee)
    val EG = Country("Egypt", "EG", "+20", Res.drawable.eg)
    val EH = Country("Western Sahara", "EH", "+212", Res.drawable.eh)
    val ER = Country("Eritrea", "ER", "+291", Res.drawable.er)
    val ES = Country("Spain", "ES", "+34", Res.drawable.es)
    val ET = Country("Ethiopia", "ET", "+251", Res.drawable.et)
    val FI = Country("Finland", "FI", "+358", Res.drawable.fi)
    val FJ = Country("Fiji", "FJ", "+679", Res.drawable.fj)
    val FK = Country("Falkland Islands (Malvinas)", "FK", "+500", Res.drawable.fk)
    val FM = Country("Micronesia, Federated States of", "FM", "+691", Res.drawable.fm)
    val FO = Country("Faroe Islands", "FO", "+298", Res.drawable.fo)
    val FR = Country("France", "FR", "+33", Res.drawable.fr)
    val GA = Country("Gabon", "GA", "+241", Res.drawable.ga)
    val GB = Country("United Kingdom", "GB", "+44", Res.drawable.gb)
    val GD = Country("Grenada", "GD", "+1", Res.drawable.gd)
    val GE = Country("Georgia", "GE", "+995", Res.drawable.ge)
    val GF = Country("French Guiana", "GF", "+594", Res.drawable.gf)
    val GG = Country("Guernsey", "GG", "+44", Res.drawable.gg)
    val GH = Country("Ghana", "GH", "+233", Res.drawable.gh)
    val GI = Country("Gibraltar", "GI", "+350", Res.drawable.gi)
    val GL = Country("Greenland", "GL", "+299", Res.drawable.gl)
    val GM = Country("Gambia", "GM", "+220", Res.drawable.gm)
    val GN = Country("Guinea", "GN", "+224", Res.drawable.gn)
    val GP = Country("Guadeloupe", "GP", "+590", Res.drawable.gp)
    val GQ = Country("Equatorial Guinea", "GQ", "+240", Res.drawable.gq)
    val GR = Country("Greece", "GR", "+30", Res.drawable.gr)
    val GS = Country("South Georgia and the South Sandwich Islands", "GS", "+500", Res.drawable.gs)
    val GT = Country("Guatemala", "GT", "+502", Res.drawable.gt)
    val GU = Country("Guam", "GU", "+1", Res.drawable.gu)
    val GW = Country("Guinea-Bissau", "GW", "+245", Res.drawable.gw)
    val GY = Country("Guyana", "GY", "+592", Res.drawable.gy)
    val HK = Country("Hong Kong", "HK", "+852", Res.drawable.hk)
    val HM = Country("Heard Island and McDonald Islands", "HM", "+672", Res.drawable.hm)
    val HN = Country("Honduras", "HN", "+504", Res.drawable.hn)
    val HR = Country("Croatia", "HR", "+385", Res.drawable.hr)
    val HT = Country("Haiti", "HT", "+509", Res.drawable.ht)
    val HU = Country("Hungary", "HU", "+36", Res.drawable.hu)
    val IC = Country("Canary Islands", "IC", "+34", Res.drawable.ic)
    val ID = Country("Indonesia", "ID", "+62", Res.drawable.id)
    val IE = Country("Ireland", "IE", "+353", Res.drawable.ie)
    val IL = Country("Israel", "IL", "+972", Res.drawable.il)
    val IM = Country("Isle of Man", "IM", "+44", Res.drawable.im)
    val IN = Country("India", "IN", "+91", Res.drawable.`in`)
    val IO = Country("British Indian Ocean Territory", "IO", "+246", Res.drawable.io)
    val IQ = Country("Iraq", "IQ", "+964", Res.drawable.iq)
    val IR = Country("Iran", "IR", "+98", Res.drawable.ir)
    val IS = Country("Iceland", "IS", "+354", Res.drawable.`is`)
    val IT = Country("Italy", "IT", "+39", Res.drawable.it)
    val JE = Country("Jersey", "JE", "+44", Res.drawable.je)
    val JM = Country("Jamaica", "JM", "+1", Res.drawable.jm)
    val JO = Country("Jordan", "JO", "+962", Res.drawable.jo)
    val JP = Country("Japan", "JP", "+81", Res.drawable.jp)
    val KE = Country("Kenya", "KE", "+254", Res.drawable.ke)
    val KG = Country("Kyrgyzstan", "KG", "+996", Res.drawable.kg)
    val KH = Country("Cambodia", "KH", "+855", Res.drawable.kh)
    val KI = Country("Kiribati", "KI", "+686", Res.drawable.ki)
    val KM = Country("Comoros", "KM", "+269", Res.drawable.km)
    val KN = Country("Saint Kitts and Nevis", "KN", "+1", Res.drawable.kn)
    val KP = Country("North Korea", "KP", "+850", Res.drawable.kp)
    val KR = Country("South Korea", "KR", "+82", Res.drawable.kr)
    val KW = Country("Kuwait", "KW", "+965", Res.drawable.kw)
    val KY = Country("Cayman Islands", "KY", "+1", Res.drawable.ky)
    val KZ = Country("Kazakhstan", "KZ", "+7", Res.drawable.kz)
    val LA = Country("Laos", "LA", "+856", Res.drawable.la)
    val LB = Country("Lebanon", "LB", "+961", Res.drawable.lb)
    val LC = Country("Saint Lucia", "LC", "+1", Res.drawable.lc)
    val LI = Country("Liechtenstein", "LI", "+423", Res.drawable.li)
    val LK = Country("Sri Lanka", "LK", "+94", Res.drawable.lk)
    val LR = Country("Liberia", "LR", "+231", Res.drawable.lr)
    val LS = Country("Lesotho", "LS", "+266", Res.drawable.ls)
    val LT = Country("Lithuania", "LT", "+370", Res.drawable.lt)
    val LU = Country("Luxembourg", "LU", "+352", Res.drawable.lu)
    val LV = Country("Latvia", "LV", "+371", Res.drawable.lv)
    val LY = Country("Libya", "LY", "+218", Res.drawable.ly)
    val MA = Country("Morocco", "MA", "+212", Res.drawable.ma)
    val MC = Country("Monaco", "MC", "+377", Res.drawable.mc)
    val MD = Country("Moldova", "MD", "+373", Res.drawable.md)
    val ME = Country("Montenegro", "ME", "+382", Res.drawable.me)
    val MF = Country("Saint Martin", "MF", "+590", Res.drawable.mf)
    val MG = Country("Madagascar", "MG", "+261", Res.drawable.mg)
    val MH = Country("Marshall Islands", "MH", "+692", Res.drawable.mh)
    val MK = Country("North Macedonia", "MK", "+389", Res.drawable.mk)
    val ML = Country("Mali", "ML", "+223", Res.drawable.ml)
    val MM = Country("Myanmar", "MM", "+95", Res.drawable.mm)
    val MN = Country("Mongolia", "MN", "+976", Res.drawable.mn)
    val MO = Country("Macau", "MO", "+853", Res.drawable.mo)
    val MP = Country("Northern Mariana Islands", "MP", "+1", Res.drawable.mp)
    val MQ = Country("Martinique", "MQ", "+596", Res.drawable.mq)
    val MR = Country("Mauritania", "MR", "+222", Res.drawable.mr)
    val MS = Country("Montserrat", "MS", "+1", Res.drawable.ms)
    val MT = Country("Malta", "MT", "+356", Res.drawable.mt)
    val MU = Country("Mauritius", "MU", "+230", Res.drawable.mu)
    val MV = Country("Maldives", "MV", "+960", Res.drawable.mv)
    val MW = Country("Malawi", "MW", "+265", Res.drawable.mw)
    val MX = Country("Mexico", "MX", "+52", Res.drawable.mx)
    val MY = Country("Malaysia", "MY", "+60", Res.drawable.my)
    val MZ = Country("Mozambique", "MZ", "+258", Res.drawable.mz)
    val NA = Country("Namibia", "NA", "+264", Res.drawable.na)
    val NC = Country("New Caledonia", "NC", "+687", Res.drawable.nc)
    val NE = Country("Niger", "NE", "+227", Res.drawable.ne)
    val NF = Country("Norfolk Island", "NF", "+672", Res.drawable.nf)
    val NG = Country("Nigeria", "NG", "+234", Res.drawable.ng)
    val NI = Country("Nicaragua", "NI", "+505", Res.drawable.ni)
    val NL = Country("Netherlands", "NL", "+31", Res.drawable.nl)
    val NO = Country("Norway", "NO", "+47", Res.drawable.no)
    val NP = Country("Nepal", "NP", "+977", Res.drawable.np)
    val NR = Country("Nauru", "NR", "+674", Res.drawable.nr)
    val NU = Country("Niue", "NU", "+683", Res.drawable.nu)
    val NZ = Country("New Zealand", "NZ", "+64", Res.drawable.nz)
    val OM = Country("Oman", "OM", "+968", Res.drawable.om)
    val PA = Country("Panama", "PA", "+507", Res.drawable.pa)
    val PE = Country("Peru", "PE", "+51", Res.drawable.pe)
    val PF = Country("French Polynesia", "PF", "+689", Res.drawable.pf)
    val PG = Country("Papua New Guinea", "PG", "+675", Res.drawable.pg)
    val PH = Country("Philippines", "PH", "+63", Res.drawable.ph)
    val PK = Country("Pakistan", "PK", "+92", Res.drawable.pk)
    val PL = Country("Poland", "PL", "+48", Res.drawable.pl)
    val PM = Country("Saint Pierre and Miquelon", "PM", "+508", Res.drawable.pm)
    val PN = Country("Pitcairn", "PN", "+870", Res.drawable.pn)
    val PR = Country("Puerto Rico", "PR", "+1", Res.drawable.pr)
    val PS = Country("State of Palestine", "PS", "+970", Res.drawable.ps)
    val PT = Country("Portugal", "PT", "+351", Res.drawable.pt)
    val PW = Country("Palau", "PW", "+680", Res.drawable.pw)
    val PY = Country("Paraguay", "PY", "+595", Res.drawable.py)
    val QA = Country("Qatar", "QA", "+974", Res.drawable.qa)
    val RE = Country("Réunion", "RE", "+262", Res.drawable.re)
    val RO = Country("Romania", "RO", "+40", Res.drawable.ro)
    val RS = Country("Serbia", "RS", "+381", Res.drawable.rs)
    val RU = Country("Russia", "RU", "+7", Res.drawable.ru)
    val RW = Country("Rwanda", "RW", "+250", Res.drawable.rw)
    val SA = Country("Saudi Arabia", "SA", "+966", Res.drawable.sa)
    val SB = Country("Solomon Islands", "SB", "+677", Res.drawable.sb)
    val SC = Country("Seychelles", "SC", "+248", Res.drawable.sc)
    val SD = Country("Sudan", "SD", "+249", Res.drawable.sd)
    val SE = Country("Sweden", "SE", "+46", Res.drawable.se)
    val SG = Country("Singapore", "SG", "+65", Res.drawable.sg)
    val SH = Country("Saint Helena, Ascension and Tristan da Cunha", "SH", "+290", Res.drawable.sh)
    val SI = Country("Slovenia", "SI", "+386", Res.drawable.si)
    val SJ = Country("Svalbard and Jan Mayen", "SJ", "+47", Res.drawable.sj)
    val SK = Country("Slovakia", "SK", "+421", Res.drawable.sk)
    val SL = Country("Sierra Leone", "SL", "+232", Res.drawable.sl)
    val SM = Country("San Marino", "SM", "+378", Res.drawable.sm)
    val SN = Country("Senegal", "SN", "+221", Res.drawable.sn)
    val SO = Country("Somalia", "SO", "+252", Res.drawable.so)
    val SR = Country("Suriname", "SR", "+597", Res.drawable.sr)
    val SS = Country("South Sudan", "SS", "+211", Res.drawable.ss)
    val ST = Country("São Tomé and Príncipe", "ST", "+239", Res.drawable.st)
    val SV = Country("El Salvador", "SV", "+503", Res.drawable.sv)
    val SX = Country("Sint Maarten", "SX", "+1", Res.drawable.sx)
    val SY = Country("Syria", "SY", "+963", Res.drawable.sy)
    val SZ = Country("Eswatini", "SZ", "+268", Res.drawable.sz)
    val TC = Country("Turks and Caicos Islands", "TC", "+1", Res.drawable.tc)
    val TD = Country("Chad", "TD", "+235", Res.drawable.td)
    val TF = Country("French Southern and Antarctic Lands", "TF", "+262", Res.drawable.tf)
    val TG = Country("Togo", "TG", "+228", Res.drawable.tg)
    val TH = Country("Thailand", "TH", "+66", Res.drawable.th)
    val TJ = Country("Tajikistan", "TJ", "+992", Res.drawable.tj)
    val TK = Country("Tokelau", "TK", "+690", Res.drawable.tk)
    val TL = Country("Timor-Leste", "TL", "+670", Res.drawable.tl)
    val TM = Country("Turkmenistan", "TM", "+993", Res.drawable.tm)
    val TN = Country("Tunisia", "TN", "+216", Res.drawable.tn)
    val TO = Country("Tonga", "TO", "+676", Res.drawable.to)
    val TR = Country("Turkey", "TR", "+90", Res.drawable.tr)
    val TT = Country("Trinidad and Tobago", "TT", "+1", Res.drawable.tt)
    val TV = Country("Tuvalu", "TV", "+688", Res.drawable.tv)
    val TW = Country("Taiwan", "TW", "+886", Res.drawable.tw)
    val TZ = Country("Tanzania", "TZ", "+255", Res.drawable.tz)
    val UA = Country("Ukraine", "UA", "+380", Res.drawable.ua)
    val UG = Country("Uganda", "UG", "+256", Res.drawable.ug)
    val UM = Country("United States Minor Outlying Islands", "UM", "+1", Res.drawable.um)
    val US = Country("United States", "US", "+1", Res.drawable.us)
    val UY = Country("Uruguay", "UY", "+598", Res.drawable.uy)
    val UZ = Country("Uzbekistan", "UZ", "+998", Res.drawable.uz)
    val VA = Country("Vatican City", "VA", "+379", Res.drawable.va)
    val VC = Country("Saint Vincent and the Grenadines", "VC", "+1", Res.drawable.vc)
    val VE = Country("Venezuela", "VE", "+58", Res.drawable.ve)
    val VG = Country("British Virgin Islands", "VG", "+1", Res.drawable.vg)
    val VI = Country("U.S. Virgin Islands", "VI", "+1", Res.drawable.vi)
    val VN = Country("Vietnam", "VN", "+84", Res.drawable.vn)
    val VU = Country("Vanuatu", "VU", "+678", Res.drawable.vu)
    val WF = Country("Wallis and Futuna", "WF", "+681", Res.drawable.wf)
    val WS = Country("Samoa", "WS", "+685", Res.drawable.ws)
    val YE = Country("Yemen", "YE", "+967", Res.drawable.ye)
    val YT = Country("Mayotte", "YT", "+262", Res.drawable.yt)
    val ZA = Country("South Africa", "ZA", "+27", Res.drawable.za)
    val ZM = Country("Zambia", "ZM", "+260", Res.drawable.zm)
    val ZW = Country("Zimbabwe", "ZW", "+263", Res.drawable.zw)

    /**
     * A list containing all predefined country instances represented by their respective properties
     * from the `Countries` object. Each entry in this list corresponds to a specific country and
     * is represented by its corresponding country object, such as `AD`, `AE`, `AF`, etc.
     *
     * This list can be used to access all the countries defined within the `Countries` object.
     */
    val ALL_COUNTRIES = listOf(
        AD, AE, AF, AG, AI, AL, AM, AO, AQ, AR,
        AS, AT, AU, AW, AX, AZ, BA, BB, BD, BE, BF, BG, BH, BI, BJ, BL, BM, BN,
        BO, BR, BS, BT, BV, BW, BY, BZ, CA, CC, CD, CF, CG, CH, CI, CK, CL, CM,
        CN, CO, CR, CU, CV, CW, CX, CY, CZ, DE, DJ, DK, DM, DZ, EAC, EC, EE, EG,
        EH, ER, ES, ET, FI, FJ, FK, FM, FO, FR, GA, GB, GD, GE, GF, GG, GH, GI, GL,
        GM, GN, GP, GQ, GR, GS, GT, GU, GW, GY, HK, HM, HN, HR, HT, HU, IC, ID, IE,
        IL, IM, IN, IO, IQ, IR, IS, IT, JE, JM, JO, JP, KE, KG, KH, KI, KM, KN, KP,
        KR, KW, KY, KZ, LA, LB, LC, LI, LK, LR, LS, LT, LU, LV, LY, MA, MC, MD, ME,
        MF, MG, MH, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY, MZ,
        NA, NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, OM, PA, PE, PF, PG, PH, PK,
        PL, PM, PN, PR, PS, PT, PW, PY, QA, RE, RO, RS, RU, RW, SA, SB, SC, SD, SE,
        SG, SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, TC, TD, TF,
        TG, TH, TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, UA, UG, UM, US, UY, UZ,
        VA, VC, VE, VG, VI, VN, VU, WF, WS, YE, YT, ZA, ZM, ZW
    )

}
